services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - cluster.name=es-cluster
      - node.name=es-node-1
      - path.data=/usr/share/elasticsearch/data
      - http.port=9200
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - ELASTIC_PASSWORD=redmond
      - xpack.security.enabled=true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - data01:/usr/share/elasticsearch/data
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://172.0.0.1:9200/_cluster/health | grep -vq '"status":"red"'
        
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=redmond
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://172.0.0.1:5601/api/status

  postgres:
    image: postgres:14-alpine
    container_name: postgres_demo
    environment:
      - POSTGRES_PASSWORD=redmond
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ProductDB
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5435:5432"
      
volumes:
  data01:
  postgres-db:
    driver: local
