version: "3.3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=redmond
      - xpack.security.enabled=true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=redmond
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
        
  postgres:
    image: postgres:14-alpine
    container_name: postgres_demo
    environment:
      - POSTGRES_PASSWORD=redmond
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ProductDB
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5433:5432"

volumes:
  esdata1:
  postgres-db:
    driver: local
