// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartELK.Infrastructure.Database;

#nullable disable

namespace SmartELK.Infrastructure.Migrations
{
    [DbContext(typeof(ProductsContext))]
    partial class ProductsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartELK.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Beverages",
                            Description = "Soft drinks, coffees, teas, beers, and ales"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Condiments",
                            Description = "Sweet and savory sauces, relishes, spreads, and seasonings"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Confections",
                            Description = "Desserts, candies, and sweet breads"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Dairy Products",
                            Description = "Cheeses, milk, and yogurts"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Grains/Cereals",
                            Description = "Breads, crackers, pasta, and cereal"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Meat/Poultry",
                            Description = "Prepared meats"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Produce",
                            Description = "Dried fruit and bean curd"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Seafood",
                            Description = "Seaweed and fish"
                        });
                });

            modelBuilder.Entity("SmartELK.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9510),
                            Description = "Handpicked beer",
                            Name = "Beer 1",
                            Price = 49.24m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9510)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9520),
                            Description = "Premium grade mustard",
                            Name = "Mustard 2",
                            Price = 48.34m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9520)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9530),
                            Description = "Authentic gummy bears",
                            Name = "Gummy Bears 3",
                            Price = 45.34m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9530)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9530),
                            Description = "Authentic cheddar cheese",
                            Name = "Cheddar Cheese 4",
                            Price = 47.18m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9530)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9530),
                            Description = "Premium grade oatmeal",
                            Name = "Oatmeal 5",
                            Price = 74.82m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9530)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9540),
                            Description = "High quality steak",
                            Name = "Steak 6",
                            Price = 37.46m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9540)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9540),
                            Description = "Delicious and fresh bananas",
                            Name = "Bananas 7",
                            Price = 9.78m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9540)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9550),
                            Description = "Top-notch crab for everyone",
                            Name = "Crab 8",
                            Price = 30.98m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9550)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9550),
                            Description = "Authentic beer",
                            Name = "Beer 9",
                            Price = 71.3m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9550)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9560),
                            Description = "Freshly made ketchup",
                            Name = "Ketchup 10",
                            Price = 93.85m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9560)
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9560),
                            Description = "Delicious and fresh lollipop",
                            Name = "Lollipop 11",
                            Price = 20.55m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9560)
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9570),
                            Description = "Exquisite milk",
                            Name = "Milk 12",
                            Price = 49.73m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9570)
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9570),
                            Description = "Exquisite corn flakes",
                            Name = "Corn Flakes 13",
                            Price = 93.39m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9570)
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9570),
                            Description = "Exquisite ham",
                            Name = "Ham 14",
                            Price = 34.37m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9570)
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9580),
                            Description = "Top-notch carrots for everyone",
                            Name = "Carrots 15",
                            Price = 65.91m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9580)
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9580),
                            Description = "Handpicked tuna",
                            Name = "Tuna 16",
                            Price = 31.71m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9580)
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9590),
                            Description = "Premium grade beer",
                            Name = "Beer 17",
                            Price = 89.56m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9590)
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9590),
                            Description = "Best in class soy sauce",
                            Name = "Soy Sauce 18",
                            Price = 47.53m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9590)
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9590),
                            Description = "Top-notch gummy bears for everyone",
                            Name = "Gummy Bears 19",
                            Price = 56.11m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9590)
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9600),
                            Description = "Premium grade cream",
                            Name = "Cream 20",
                            Price = 30.5m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9600)
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9600),
                            Description = "Authentic oatmeal",
                            Name = "Oatmeal 21",
                            Price = 43.44m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9600)
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9610),
                            Description = "Delicious and fresh turkey",
                            Name = "Turkey 22",
                            Price = 14.71m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9610)
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9610),
                            Description = "Top-notch bananas for everyone",
                            Name = "Bananas 23",
                            Price = 18.68m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9610)
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9610),
                            Description = "Premium grade shrimp",
                            Name = "Shrimp 24",
                            Price = 73.3m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9610)
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9620),
                            Description = "High quality green tea",
                            Name = "Green Tea 25",
                            Price = 95.57m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9620)
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9620),
                            Description = "Top-notch soy sauce for everyone",
                            Name = "Soy Sauce 26",
                            Price = 30.34m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9620)
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9620),
                            Description = "Exquisite chocolate bar",
                            Name = "Chocolate Bar 27",
                            Price = 20.02m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9630)
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9630),
                            Description = "Premium grade milk",
                            Name = "Milk 28",
                            Price = 91.79m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9630)
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9630),
                            Description = "Exquisite spaghetti",
                            Name = "Spaghetti 29",
                            Price = 38.52m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9630)
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9640),
                            Description = "Top-notch turkey for everyone",
                            Name = "Turkey 30",
                            Price = 3.8m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9640)
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9680),
                            Description = "Top-notch apples for everyone",
                            Name = "Apples 31",
                            Price = 91.84m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9680)
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9690),
                            Description = "Top-notch salmon for everyone",
                            Name = "Salmon 32",
                            Price = 7.05m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9690)
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9690),
                            Description = "High quality beer",
                            Name = "Beer 33",
                            Price = 65.5m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9690)
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9700),
                            Description = "Freshly made mustard",
                            Name = "Mustard 34",
                            Price = 47.48m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9700)
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9700),
                            Description = "Authentic chocolate bar",
                            Name = "Chocolate Bar 35",
                            Price = 36.13m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9700)
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9700),
                            Description = "Authentic cream",
                            Name = "Cream 36",
                            Price = 28.58m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9700)
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9710),
                            Description = "Top-notch corn flakes for everyone",
                            Name = "Corn Flakes 37",
                            Price = 64.04m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9710)
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9710),
                            Description = "Organic and natural chicken breast",
                            Name = "Chicken Breast 38",
                            Price = 36.64m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9710)
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9720),
                            Description = "Top-notch apples for everyone",
                            Name = "Apples 39",
                            Price = 49.22m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9720)
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9720),
                            Description = "Delicious and fresh shrimp",
                            Name = "Shrimp 40",
                            Price = 49.52m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9720)
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9720),
                            Description = "Freshly made beer",
                            Name = "Beer 41",
                            Price = 17.68m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9720)
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9730),
                            Description = "Best in class soy sauce",
                            Name = "Soy Sauce 42",
                            Price = 33.36m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9730)
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9730),
                            Description = "Top-notch chocolate bar for everyone",
                            Name = "Chocolate Bar 43",
                            Price = 16.08m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9730)
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9730),
                            Description = "Exquisite milk",
                            Name = "Milk 44",
                            Price = 24.6m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9730)
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9740),
                            Description = "Exquisite spaghetti",
                            Name = "Spaghetti 45",
                            Price = 72.06m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9740)
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9740),
                            Description = "Exquisite ham",
                            Name = "Ham 46",
                            Price = 62.06m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9740)
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9740),
                            Description = "Freshly made spinach",
                            Name = "Spinach 47",
                            Price = 45.23m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9740)
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9750),
                            Description = "Authentic salmon",
                            Name = "Salmon 48",
                            Price = 28.37m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9750)
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9750),
                            Description = "Freshly made beer",
                            Name = "Beer 49",
                            Price = 3.79m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9750)
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9750),
                            Description = "Exquisite hot sauce",
                            Name = "Hot Sauce 50",
                            Price = 51.72m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9760)
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9760),
                            Description = "Premium grade cheesecake",
                            Name = "Cheesecake 51",
                            Price = 41.75m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9760)
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9760),
                            Description = "Top-notch yogurt for everyone",
                            Name = "Yogurt 52",
                            Price = 41.89m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9760)
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9770),
                            Description = "Delicious and fresh oatmeal",
                            Name = "Oatmeal 53",
                            Price = 81.45m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9770)
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9770),
                            Description = "Handpicked steak",
                            Name = "Steak 54",
                            Price = 85.64m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9770)
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9770),
                            Description = "Top-notch broccoli for everyone",
                            Name = "Broccoli 55",
                            Price = 35.37m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9770)
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9780),
                            Description = "Exquisite crab",
                            Name = "Crab 56",
                            Price = 56.39m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9780)
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9780),
                            Description = "Top-notch cola for everyone",
                            Name = "Cola 57",
                            Price = 18.86m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9780)
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9780),
                            Description = "Organic and natural bbq sauce",
                            Name = "BBQ Sauce 58",
                            Price = 15.6m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9780)
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9790),
                            Description = "Premium grade gummy bears",
                            Name = "Gummy Bears 59",
                            Price = 58.66m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9790)
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9790),
                            Description = "Organic and natural yogurt",
                            Name = "Yogurt 60",
                            Price = 83.12m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9790)
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9800),
                            Description = "Best in class rice",
                            Name = "Rice 61",
                            Price = 63.49m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9800)
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9800),
                            Description = "Authentic turkey",
                            Name = "Turkey 62",
                            Price = 58.07m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9800)
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9800),
                            Description = "High quality broccoli",
                            Name = "Broccoli 63",
                            Price = 61.74m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9800)
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9840),
                            Description = "Premium grade shrimp",
                            Name = "Shrimp 64",
                            Price = 29.06m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9840)
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9840),
                            Description = "Top-notch beer for everyone",
                            Name = "Beer 65",
                            Price = 51.67m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9840)
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9850),
                            Description = "Delicious and fresh ketchup",
                            Name = "Ketchup 66",
                            Price = 51.53m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9850)
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9850),
                            Description = "Organic and natural lollipop",
                            Name = "Lollipop 67",
                            Price = 15.93m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9850)
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9860),
                            Description = "Authentic cream",
                            Name = "Cream 68",
                            Price = 84.98m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9860)
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9860),
                            Description = "Delicious and fresh oatmeal",
                            Name = "Oatmeal 69",
                            Price = 63.87m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9860)
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9860),
                            Description = "Top-notch turkey for everyone",
                            Name = "Turkey 70",
                            Price = 11.97m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9860)
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9870),
                            Description = "Freshly made bananas",
                            Name = "Bananas 71",
                            Price = 24.95m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9870)
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9870),
                            Description = "Exquisite lobster",
                            Name = "Lobster 72",
                            Price = 95.18m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9870)
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9870),
                            Description = "Exquisite coffee",
                            Name = "Coffee 73",
                            Price = 22.33m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9870)
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9880),
                            Description = "Handpicked soy sauce",
                            Name = "Soy Sauce 74",
                            Price = 9.69m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9880)
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9880),
                            Description = "Freshly made chocolate bar",
                            Name = "Chocolate Bar 75",
                            Price = 55.9m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9880)
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9880),
                            Description = "Best in class yogurt",
                            Name = "Yogurt 76",
                            Price = 14.9m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9890)
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9890),
                            Description = "High quality spaghetti",
                            Name = "Spaghetti 77",
                            Price = 19.69m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9890)
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9890),
                            Description = "Premium grade bacon",
                            Name = "Bacon 78",
                            Price = 2.03m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9890)
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9900),
                            Description = "Freshly made spinach",
                            Name = "Spinach 79",
                            Price = 48.94m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9900)
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9900),
                            Description = "Handpicked salmon",
                            Name = "Salmon 80",
                            Price = 83.89m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9900)
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9900),
                            Description = "Premium grade coffee",
                            Name = "Coffee 81",
                            Price = 3.13m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9900)
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9910),
                            Description = "Handpicked bbq sauce",
                            Name = "BBQ Sauce 82",
                            Price = 71.99m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9910)
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9910),
                            Description = "Handpicked cheesecake",
                            Name = "Cheesecake 83",
                            Price = 41.05m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9910)
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9910),
                            Description = "High quality milk",
                            Name = "Milk 84",
                            Price = 74.41m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9910)
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9920),
                            Description = "Delicious and fresh spaghetti",
                            Name = "Spaghetti 85",
                            Price = 7.15m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9920)
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9920),
                            Description = "Delicious and fresh turkey",
                            Name = "Turkey 86",
                            Price = 41.13m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9920)
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9930),
                            Description = "Premium grade carrots",
                            Name = "Carrots 87",
                            Price = 98.51m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9930)
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9930),
                            Description = "Top-notch salmon for everyone",
                            Name = "Salmon 88",
                            Price = 48.83m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9930)
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9930),
                            Description = "Best in class orange juice",
                            Name = "Orange Juice 89",
                            Price = 36.72m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9930)
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9940),
                            Description = "Best in class mustard",
                            Name = "Mustard 90",
                            Price = 98.77m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9940)
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9940),
                            Description = "Best in class chocolate bar",
                            Name = "Chocolate Bar 91",
                            Price = 40.91m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9940)
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9940),
                            Description = "Delicious and fresh cheddar cheese",
                            Name = "Cheddar Cheese 92",
                            Price = 36.82m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9940)
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9950),
                            Description = "Delicious and fresh rice",
                            Name = "Rice 93",
                            Price = 85.34m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 343, DateTimeKind.Utc).AddTicks(9950)
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 344, DateTimeKind.Utc).AddTicks(30),
                            Description = "Organic and natural ham",
                            Name = "Ham 94",
                            Price = 2.85m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 344, DateTimeKind.Utc).AddTicks(30)
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 344, DateTimeKind.Utc).AddTicks(40),
                            Description = "Organic and natural broccoli",
                            Name = "Broccoli 95",
                            Price = 46.52m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 344, DateTimeKind.Utc).AddTicks(40)
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 344, DateTimeKind.Utc).AddTicks(40),
                            Description = "High quality lobster",
                            Name = "Lobster 96",
                            Price = 91.12m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 344, DateTimeKind.Utc).AddTicks(40)
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 344, DateTimeKind.Utc).AddTicks(40),
                            Description = "Best in class beer",
                            Name = "Beer 97",
                            Price = 48.09m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 344, DateTimeKind.Utc).AddTicks(50)
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 344, DateTimeKind.Utc).AddTicks(50),
                            Description = "Authentic ketchup",
                            Name = "Ketchup 98",
                            Price = 90.25m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 344, DateTimeKind.Utc).AddTicks(50)
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 344, DateTimeKind.Utc).AddTicks(50),
                            Description = "Premium grade chocolate bar",
                            Name = "Chocolate Bar 99",
                            Price = 82.57m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 344, DateTimeKind.Utc).AddTicks(50)
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 344, DateTimeKind.Utc).AddTicks(60),
                            Description = "High quality milk",
                            Name = "Milk 100",
                            Price = 6.74m,
                            UpdatedAt = new DateTime(2024, 6, 4, 16, 7, 29, 344, DateTimeKind.Utc).AddTicks(60)
                        });
                });

            modelBuilder.Entity("SmartELK.Domain.Entities.Product", b =>
                {
                    b.HasOne("SmartELK.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SmartELK.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
